### ISSUE TITLE
Missing values from the ANCOM V2.1 for the ANCOM-BC analysis

### ISSUE THREAD

**Issue by BinhongLiu** [FrederickHuangLin/ANCOM-BC-Code-Archive#4]
Hi,
    Thank you for the development of this useful tool!
    I just found that the feature table pre-processed with the function _feature_table_pre_process_ derived from the ANCOM v2.1 had no values like group.name, neither group.ind. Could you help me with this mismatch values?
    Thanks!
Hongbin Liu

**Comment by FrederickHuangLin** [comment]
Hi @BinhongLiu,

Thanks for your interest in ANCOM and ANCOM-BC.

Since ANCOM and ANCOM-BC are still developing, there are indeed some inconsistencies in their helper functions, sorry for the inconvenience. 

For your information, this repository is for archive only, the corresponding ANCOMBC R package has been published in Bioconductor and is actively maintained [here](https://github.com/FrederickHuangLin/ANCOMBC).

Best,

Huang
